### Get all zens
GET http://localhost:8000/zen

### Get all zens given collection and zen name
GET http://localhost:8000/collections/production/zen/state_filter/

### Create a new zen
PUT http://localhost:8000/collections/production/zen/state_filter
Content-Type: application/json

{
  "version": "2",
  "description": "Testing new api",
  "query": "SELECT * FROM whatever"
}