# Generated by Django 5.1.5 on 2025-01-28 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryZen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('query', models.TextField()),
                ('version', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('VA', 'Valid'), ('IN', 'Invalid')], default='VA', max_length=2)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('VA', 'Valid'), ('IN', 'Invalid')], max_length=2)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('zen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.queryzen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
