# Generated by Django 5.1.6 on 2025-02-10 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('query', models.TextField()),
                ('default_parameters', models.JSONField(null=True)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('VA', 'Valid'), ('IN', 'Invalid'), ('UN', 'UNKNOWN')], default='UN', max_length=2)),
            ],
            options={
                'unique_together': {('collection', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('VA', 'Valid'), ('IN', 'Invalid')], max_length=2)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
                ('total_time', models.IntegerField()),
                ('query', models.TextField()),
                ('error', models.TextField()),
                ('row_count', models.SmallIntegerField()),
                ('parameters', models.TextField()),
                ('zen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.zen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
