# Generated by Django 5.1.5 on 2025-01-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='zen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.queryzen'),
        ),
    ]
