# Generated by Django 5.1.6 on 2025-02-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='execution_time',
            new_name='execution_time_in_ms',
        ),
    ]
