# Generated by Django 5.1.5 on 2025-02-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_queryzen_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryzen',
            name='version',
            field=models.IntegerField(),
        ),
    ]
