# Generated by Django 5.1.5 on 2025-02-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_queryzen_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='query',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
