# Generated by Django 5.1.5 on 2025-02-05 20:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_execution_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('query', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('VA', 'Valid'), ('IN', 'Invalid'), ('UN', 'UNKNOWN')], default='UN', max_length=2)),
            ],
            options={
                'unique_together': {('collection', 'name', 'version')},
            },
        ),
        migrations.AlterField(
            model_name='execution',
            name='zen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.zen'),
        ),
        migrations.DeleteModel(
            name='QueryZen',
        ),
    ]
