# Generated by Django 5.1.5 on 2025-01-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('version', models.TextField()),
            ],
        ),
    ]
