# Generated by Django 5.1.5 on 2025-01-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lambdaquery_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LambdaQuery',
            new_name='QueryLambda',
        ),
    ]
