name: Lint code

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest

    - name: Run pylint on code
      run: |
        pylint $(git ls-files '*.py') > pylint_report.txt || true
        echo "report<<EOF" >> $GITHUB_ENV
        cat pylint_report.txt >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create GitHub Issue
      if: env.report != ''
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: "Pylint Issues Detected on ${{ github.sha }}"
        content-filepath: pylint_report.txt
        labels: "lint"

    - name: Unittests
      run: |
        pytest